# Generated by Django 4.0.1 on 2022-01-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'gallery'},
        ),
        migrations.AddField(
            model_name='place',
            name='place',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
